//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgPart2Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int courseID { get; set; }
        public int userID { get; set; }
        public string courseName { get; set; }
        public string courseCode { get; set; }
        public int credits { get; set; }
        public int classHours { get; set; }
        public int semesterWeeks { get; set; }
        public int hoursRemaining { get; set; }
        public int selfStudyHoursPerWeek { get; set; }
        public int day { get; set; }
        public int month { get; set; }
        public int hoursWorked { get; set; }
        public System.DateTime startDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
